
package com.owncloud.android.utils

const val DOWNLOAD_NOTIFICATION_CHANNEL_ID = "DOWNLOAD_NOTIFICATION_CHANNEL"
const val UPLOAD_NOTIFICATION_CHANNEL_ID = "UPLOAD_NOTIFICATION_CHANNEL"
const val MEDIA_SERVICE_NOTIFICATION_CHANNEL_ID = "MEDIA_SERVICE_NOTIFICATION_CHANNEL"
const val FILE_SYNC_CONFLICT_NOTIFICATION_CHANNEL_ID = "FILE_SYNC_CONFLICT_CHANNEL_ID"
const val FILE_SYNC_NOTIFICATION_CHANNEL_ID = "FILE_SYNC_NOTIFICATION_CHANNEL"

const val DOWNLOAD_NOTIFICATION_ID_DEFAULT = 123

const val NOTIFICATION_TIMEOUT_STANDARD = 2_000L
