

package com.owncloud.android.utils

enum class Permissions(val value: Int) {
    READ_PERMISSIONS(1),
    EDIT_PERMISSIONS(3),
    SHARE_PERMISSIONS(17),
    ALL_PERMISSIONS(19),

    EDIT_CREATE_PERMISSIONS(5),
    EDIT_CREATE_CHANGE_PERMISSIONS(7),
    EDIT_CREATE_DELETE_PERMISSIONS(13),
    EDIT_CREATE_CHANGE_DELETE_PERMISSIONS(15),
    EDIT_CHANGE_PERMISSIONS(3),
    EDIT_CHANGE_DELETE_PERMISSIONS(11),
    EDIT_DELETE_PERMISSIONS(9),
}
